# Generated by Django 4.1.7 on 2023-05-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('precio', models.FloatField()),
                ('recamaras', models.IntegerField()),
                ('banos', models.IntegerField()),
            ],
        ),
    ]
