# Generated by Django 4.1.7 on 2023-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='colonia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
