# Generated by Django 4.1.7 on 2023-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_casa_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='vendida',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
