# Generated by Django 4.1.7 on 2023-05-15 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0004_casa_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.casa')),
            ],
        ),
    ]
