# Generated by Django 4.1.7 on 2023-05-16 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0006_remove_casa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencasa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='casas.casa'),
        ),
    ]
