# Generated by Django 4.1.7 on 2023-05-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0007_alter_imagencasa_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagencasa',
            old_name='producto',
            new_name='casa',
        ),
        migrations.AlterField(
            model_name='imagencasa',
            name='imagen',
            field=models.ImageField(upload_to='casas'),
        ),
    ]
