# Generated by Django 4.1.7 on 2023-05-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0009_casa_latitud_casa_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='metros',
            field=models.CharField(default='100', max_length=50),
        ),
    ]
