# Generated by Django 4.1.7 on 2023-05-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0011_alter_casa_metros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(verbose_name=10)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='casas.casa')),
            ],
        ),
    ]
