# Generated by Django 4.1.7 on 2023-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0012_clientecasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecasa',
            name='telefono',
            field=models.IntegerField(max_length=10),
        ),
    ]
