# Generated by Django 4.1.7 on 2023-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0013_alter_clientecasa_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientecasa',
            old_name='casa',
            new_name='casaid',
        ),
        migrations.AlterField(
            model_name='clientecasa',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
