# Generated by Django 4.1.7 on 2023-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0015_rename_casaid_clientecasa_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecasa',
            name='correo',
            field=models.CharField(max_length=100),
        ),
    ]
