# Generated by Django 4.1.7 on 2023-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0016_alter_clientecasa_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecasa',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
